/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as HistoryScanIdIndexRouteImport } from './routes/history/$scanId/index'
import { Route as HistoryScanIdPagesPageIdRouteImport } from './routes/history/$scanId/pages/$pageId'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryScanIdIndexRoute = HistoryScanIdIndexRouteImport.update({
  id: '/history/$scanId/',
  path: '/history/$scanId/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryScanIdPagesPageIdRoute =
  HistoryScanIdPagesPageIdRouteImport.update({
    id: '/history/$scanId/pages/$pageId',
    path: '/history/$scanId/pages/$pageId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tasks': typeof TasksRoute
  '/history': typeof HistoryIndexRoute
  '/history/$scanId': typeof HistoryScanIdIndexRoute
  '/history/$scanId/pages/$pageId': typeof HistoryScanIdPagesPageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tasks': typeof TasksRoute
  '/history': typeof HistoryIndexRoute
  '/history/$scanId': typeof HistoryScanIdIndexRoute
  '/history/$scanId/pages/$pageId': typeof HistoryScanIdPagesPageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tasks': typeof TasksRoute
  '/history/': typeof HistoryIndexRoute
  '/history/$scanId/': typeof HistoryScanIdIndexRoute
  '/history/$scanId/pages/$pageId': typeof HistoryScanIdPagesPageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tasks'
    | '/history'
    | '/history/$scanId'
    | '/history/$scanId/pages/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tasks'
    | '/history'
    | '/history/$scanId'
    | '/history/$scanId/pages/$pageId'
  id:
    | '__root__'
    | '/'
    | '/tasks'
    | '/history/'
    | '/history/$scanId/'
    | '/history/$scanId/pages/$pageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TasksRoute: typeof TasksRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  HistoryScanIdIndexRoute: typeof HistoryScanIdIndexRoute
  HistoryScanIdPagesPageIdRoute: typeof HistoryScanIdPagesPageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$scanId/': {
      id: '/history/$scanId/'
      path: '/history/$scanId'
      fullPath: '/history/$scanId'
      preLoaderRoute: typeof HistoryScanIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$scanId/pages/$pageId': {
      id: '/history/$scanId/pages/$pageId'
      path: '/history/$scanId/pages/$pageId'
      fullPath: '/history/$scanId/pages/$pageId'
      preLoaderRoute: typeof HistoryScanIdPagesPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TasksRoute: TasksRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  HistoryScanIdIndexRoute: HistoryScanIdIndexRoute,
  HistoryScanIdPagesPageIdRoute: HistoryScanIdPagesPageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
