/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as HistoryIndexImport } from './routes/history/index'
import { Route as HistoryScanIdIndexImport } from './routes/history/$scanId/index'
import { Route as HistoryScanIdPagesPageIdImport } from './routes/history/$scanId/pages/$pageId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HistoryIndexRoute = HistoryIndexImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRoute,
} as any)

const HistoryScanIdIndexRoute = HistoryScanIdIndexImport.update({
  id: '/history/$scanId/',
  path: '/history/$scanId/',
  getParentRoute: () => rootRoute,
} as any)

const HistoryScanIdPagesPageIdRoute = HistoryScanIdPagesPageIdImport.update({
  id: '/history/$scanId/pages/$pageId',
  path: '/history/$scanId/pages/$pageId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryIndexImport
      parentRoute: typeof rootRoute
    }
    '/history/$scanId/': {
      id: '/history/$scanId/'
      path: '/history/$scanId'
      fullPath: '/history/$scanId'
      preLoaderRoute: typeof HistoryScanIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/history/$scanId/pages/$pageId': {
      id: '/history/$scanId/pages/$pageId'
      path: '/history/$scanId/pages/$pageId'
      fullPath: '/history/$scanId/pages/$pageId'
      preLoaderRoute: typeof HistoryScanIdPagesPageIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryIndexRoute
  '/history/$scanId': typeof HistoryScanIdIndexRoute
  '/history/$scanId/pages/$pageId': typeof HistoryScanIdPagesPageIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryIndexRoute
  '/history/$scanId': typeof HistoryScanIdIndexRoute
  '/history/$scanId/pages/$pageId': typeof HistoryScanIdPagesPageIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/history/': typeof HistoryIndexRoute
  '/history/$scanId/': typeof HistoryScanIdIndexRoute
  '/history/$scanId/pages/$pageId': typeof HistoryScanIdPagesPageIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/history/$scanId'
    | '/history/$scanId/pages/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/history' | '/history/$scanId' | '/history/$scanId/pages/$pageId'
  id:
    | '__root__'
    | '/'
    | '/history/'
    | '/history/$scanId/'
    | '/history/$scanId/pages/$pageId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  HistoryScanIdIndexRoute: typeof HistoryScanIdIndexRoute
  HistoryScanIdPagesPageIdRoute: typeof HistoryScanIdPagesPageIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  HistoryScanIdIndexRoute: HistoryScanIdIndexRoute,
  HistoryScanIdPagesPageIdRoute: HistoryScanIdPagesPageIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/history/",
        "/history/$scanId/",
        "/history/$scanId/pages/$pageId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/history/": {
      "filePath": "history/index.tsx"
    },
    "/history/$scanId/": {
      "filePath": "history/$scanId/index.tsx"
    },
    "/history/$scanId/pages/$pageId": {
      "filePath": "history/$scanId/pages/$pageId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
